### PR TITLE
Add patch from PR 256

### PR DESCRIPTION
**Pull request by stertingen**
Add fix from PR https://github.com/ros/ros/pull/256.

### CODE REVIEW

**Comment by acxz** [comment]
Nice, let's add it in!

**Comment by acxz** [comment]
@stertingen also while I have your attention, would you be interested in helping the ros-arch team create the ros-noetic packages?

**Comment by stertingen** [comment]
> @stertingen also while I have your attention, would you be interested in helping the ros-arch team create the ros-noetic packages?

Thanks, I'd be honored to!

**Comment by acxz** [comment]
Sweet!

**Pull request merged**
